version: '3.7'

networks:
    db_network:
        external: true

services:
    postgres:
        build: ./
        volumes:
            - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
            #- ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
           - "${POSTGRES_PORT}:5432"
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        restart: always
        networks:
          - db_network

